### ISSUE TITLE
keys no longer checking extra keys

### ISSUE THREAD

**Issue by kurayama** [shouldjs/should.js#132] opened 2017-01-05 12:41 UTC
## Node.js version?
7

## Should.js version?
11

## How to reproduce it?
`({a: 1, b:2}).should.have.keys('a')` does not throw.

`keys` had its behavior changed on https://github.com/shouldjs/should.js/commit/73fc861fa15dd694c5cf2b5cb187c459ebe181d1 where no longer checks for extra keys and behaves the same way as `properties` which doesn't seem like the expected behavior.

**Comment by btd** [comment] 2017-01-05 16:53
Hi, it was breaking change for 11.x. It was required to unify interface of .keys/.key for Map/Set/WeakMap/WeakSet and plain objects.
You are first person, i see ever complained about this functionality. 
As a simple workaround you can use .key + .length check.
Could you describe your use case maybe i could suggest something more suitable?

**Comment by kurayama** [comment] 2017-01-05 17:53
Our use case is to assert that a json response has exactly a set of keys.

**Comment by btd** [comment] 2017-01-05 17:57
So, yes i would suggest you to use this 2 assertions, like this:
```js
Assertion.add('onlyKeys', function(...keys) {
  this.obj.should.have.keys(...keys).and.have.length(keys.length);
});
// this is what previous keys did
```

**Comment by ruimarinho** [comment] 2017-01-06 00:03
I don't think the argument of unifying `.keys/.key` for `Map/Set/WeakMap/WeakSet` should have any impact on public interface besides adding support for those types. Even if it makes complete sense considering the way the code works internally, that should not be the reason to break a completely valid assertion differentiation IMHO.

Right now (11+), I feel `.keys` is just a crippled and therefore less useful version of `.properties`, so I would deprecate the former as part of the BC.?

What about `({ a: 1, b: 2 }).should.have.exactly.properties('a', 'b')` as an alternative?

**Comment by btd** [comment] 2017-01-06 10:02
@ruimarinho that is a purpose of major version change.
`properties` are not `keys`. Even if for plain object case, `keys` it is subset of `properties` for other key-value objects it is not - this is a huge difference. Main purpose for this BC was differentiate k-v structures from plain objects.

Thus `.properties` **always** work on plain objects. But `.keys` now work on k-v object structure. 
Your proposal does not makes sense to me (exctly props - keys is not properties). As i said prev `.keys` easy emulated with `.keys` + `.length`.

**Comment by ruimarinho** [comment] 2017-01-06 11:02
Don't get me wrong, I'm not against BC or major versions if the outcome is positive. Supporting `Map/Set/WeakMap/WeakSet` is certainly welcome.

In the end, the overlap between `.keys` and `.properties` is so large that there's is no point in keeping both. I've been using `should.js` for a long time now and this was the first BC that really confused me, so I guess it will be even worse for new users.

It's a pity that a perfectly valid and understandable assertion now requires a custom assertion, but that's up to you.

**Comment by btd** [comment] 2017-01-06 11:28
I am trying to listen feedback always. But I see several invalid points in yours:
1. `.key` and `.properties` is not the same. For objects `.key` is a almost `.ownProperty`. And for others it is not. So `.keys` is a 2 assertions internally for objects (it is prorperty and own property, while property only checks if it is property). So i do not see overlap.
2. you seem agree that supporting Map, Set is good. But to make unified assertion interface it is clear that `.keys` must be changed. So you just skipping this point.
3. Previous `.keys` did 2 assertions: 1 checks if object has passed keys, 2 no more extra keys. It maybe valid, but it also makes sense to simplify it. That is way it is easy to workaround this.
4. Point about confusion and new users is very subjecting - i do not think it should be discussed. All users can create issue or write to gitter chat. 

As a side note this change allowed easy extend should.js to immutable.js structures.
So if you could suggest something i am open to listen. But curretly you are saing, this BC is bad and that is all.

**Comment by rplopes** [comment] 2017-01-13 18:34
I believe the problem is the old behaviour led people to use `.keys` for asserting an exact match, and `.properties` for asserting a partial one. So we'd have:

```js
> ({ a: 1, b: 2 }).should.have.keys('a');
false
> ({ a: 1, b: 2 }).should.have.properties('a');
true
```

In hindsight, this approach doesn't look very correct, because it's just making use of a probably unintended side-effect. This difference is certainly not obvious for newer devs.

However, it would still be important to have some method for asserting the exact match of keys/properties. I see this being extremely important in use cases such as asserting an API response doesn't expose unintended information, or that an object doesn't get additional properties merged at some point.

So the above code could probably change to something like:

```js
> ({ a: 1, b: 2 }).should.have.only.keys('a');
false
> ({ a: 1, b: 2 }).should.have.keys('a');
true
```

Does this make sense? Would it be something useful for should.js to have, considering this important feature was lost in this breaking change?

**Comment by btd** [comment] 2017-01-13 19:07
Yes this make sense. I am :+1: about adding it. But i would like to avoid if possible to add additional flags like .only (we already have .any and it creates some problems). Let me think about it more. Probably .only flag would be right approach

**Comment by ruimarinho** [comment] 2017-01-13 23:35
@btd any chance of using `.exactly.keys`? Seems very intuitive to me (as an old should.js user), allows for the existing BC supports Maps/Sets/WeakM* but also clear to anyone who is new to it.

**Comment by btd** [comment] 2017-01-19 11:04
Sorry for taking this so long, very busy at work.

@ruimarinho `.exactly` will not work currently because it is alias for `.equal`. Literally this name already in use.

**Comment by ruimarinho** [comment] 2017-01-22 23:48
@btd no problem, take your time. So the best proposal for now is  `should.have.only.keys()`?

**Comment by btd** [comment] 2017-01-27 08:35
I just published 11.2.0. It has .only support

**Comment by rplopes** [comment] 2017-01-28 23:27
That's great, cheers!

**Comment by btd** [comment] 2017-01-30 15:03
Closing this, let me know please if anything.

**Closed by btd** 2017-01-30 15:03 UTC
Labels: discussion, enhancement

**Comment by ruimarinho** [comment] 2017-01-31 00:03
Thank you @btd.
