### ISSUE TITLE
wierd recursion loop 

### ISSUE THREAD

**Issue by osher** [shouldjs/should.js#123] opened 2016-10-10 10:53 UTC
## Node.js version?
6.5.0

## Should.js version?
11.1.0

## How to reproduce it?
First I observed that some tests I run fail, but I do not see the exception as part of the test fail.
I'm running in `mocha`, and using `mocha-ui-exports` and `mocha-ui-exports-request`, but, to describe the problem in isolation I'll try the following simplification:

The test that failed, part of a test-suite factory:
```
if (expect.statusCode || expect.status) {
    it("should return status " + expect.status,  function() {
        res.should.have.property('statusCode', expect.statusCode || expect.status);
    });
}
```
where `res` is a response object (`http.IncomingMessage`) obtained using `request/request` during the `breforeAll` hook on the same level.

Running it as is - I don't get the exceptions list in the end of the report.
But, when I tried the following:
```
if (expect.statusCode || expect.status)  {
    it("should return status " + expect.status,  function() {
        try {
            res.should.have.property('statusCode', expect.statusCode || expect.status);
        } catch(e) { throw new Error(e.stack) }
    });
}
```
I got 
```
 Error: <error: RangeError: Maximum call stack size exceeded>
      at Assertion.fail (node_modules\should\cjs\should.js:205:17)
      at Assertion.value [as property] (node_modules\should\cjs\should.js:277:19)
      at Object.suite.(anonymous function) [as should return status 200] (node_modules\mocha-ui-exports-request\index.js:54:35)
      at Context.should return status 200 (test\lib.web.operations.locale_POST.test.js:51:46)
      at Context.should return status 200 (test\lib.web.operations.locale_POST.test.js:53:19)
```

and when I tried 
```
if (expect.statusCode || expect.status)  {
    it("should return status " + expect.status,  function() {
        try {
            res.should.have.property('statusCode', expect.statusCode || expect.status);
        } catch(e) { throw new Error(e.message) }
    });
}
```

I got the attached output: [should.bug.txt](https://github.com/shouldjs/should.js/files/519314/should.bug.txt)

I hope that's enough info, I'll try to be responsive and provide more data if needed

**Comment by osher** [comment] 2016-10-10 10:56
P.S
The bug is not reproduced with `should@9.x` nor with `should@10.x`, so I downgraded to v10 for now

**Comment by btd** [comment] 2016-10-10 11:13
Hi.

Can you please help me create reproduction example (because it is not simple reqursion in object value).
I tried with this:

```js
var request = require('request');
var should = require('should');

request('http://www.google.com', function(err, res) {
  try {
    res.should.have.property('statusCode', 200);
  } catch (e) {
    console.log(e.stack);
  }
  console.log('executed successfully')
});
```

**Comment by osher** [comment] 2016-10-10 11:48
let me peel the secret sauce from the project, I'll try to upload a zip shortly

**Comment by osher** [comment] 2016-10-10 12:18
[reproduce.zip](https://github.com/shouldjs/should.js/files/519444/reproduce.zip)

1) `npm install`
2) `mocha`

Mind that there are 6 failing tests, but only 3 exceptions in the following report

**Comment by osher** [comment] 2016-10-10 12:19
let me know that you can open it and the reproduction works for you

**Comment by osher** [comment] 2016-10-10 12:22
LOL!!!
I just saw that your original example just doesn't fail the assert...

```
var request = require('request');
var should = require('should');

request('http://www.google.com', function(err, res) {
  try {
    res.should.have.property('statusCode', 999); //TRICKY: 999 - no such code, will fail the assert
  } catch (e) {
    console.log(e.stack);
  }
  console.log('executed successfully')
});

```

**Comment by btd** [comment] 2016-10-10 13:18
Thanks, a lot. This really helped (not sure how i missed that assertion passed =).
Please give a try to 11.1.1. I have just published it.

**Comment by btd** [comment] 2016-10-11 13:55
@osher any updates?

**Comment by btd** [comment] 2016-10-14 09:12
Closing this, feel free to reopen if need.

**Closed by btd** 2016-10-14 09:12 UTC
